<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class MockDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        $password = Hash::make('password123');

        // 1. Departments
        $extraDepartments = [
            'Human Resources',
            'Finance & Accounting',
            'Sales & Business Development',
            'Product & UX Design',
            'Quality Assurance'
        ];
        foreach ($extraDepartments as $dept) {
            if (!DB::table('departments')->where('department', $dept)->exists()) {
                DB::table('departments')->insert([
                    'department' => $dept,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }

        // 2. Position Types / Designations
        $extraPositions = [
            'Lead Architect',
            'Senior Full-Stack Developer',
            'UI/UX Lead Designer',
            'QA Lead Engineer',
            'DevOps Specialist',
            'HR Director',
            'Talent Acquisition Lead',
            'Senior Financial Accountant',
            'Product Manager'
        ];
        foreach ($extraPositions as $pos) {
            if (!DB::table('position_types')->where('position', $pos)->exists()) {
                DB::table('position_types')->insert([
                    'position' => $pos,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }

        // 3. Company Settings
        DB::table('company_settings')->updateOrInsert(
            ['id' => 1],
            [
                'company_name'   => 'Apex Horizon Technologies Inc.',
                'contact_person' => 'Jayy',
                'address'        => '100 Innovation Boulevard, Tech Park Suite 400',
                'country'        => 'United States',
                'city'           => 'San Francisco',
                'state_province' => 'California',
                'postal_code'    => '94107',
                'email'          => 'contact@apexhorizon.io',
                'phone_number'   => '+1 (415) 890-1200',
                'mobile_number'  => '+1 (415) 890-1201',
                'fax'            => '+1 (415) 890-1202',
                'website_url'    => 'https://apexhorizon.io',
                'created_at'     => $now,
                'updated_at'     => $now,
            ]
        );

        // 4. Users and Employees
        // Retain or update existing Jayy (KH-0001)
        $existingJayy = DB::table('users')->where('id', 1)->first();
        if ($existingJayy) {
            DB::table('users')->where('id', 1)->update([
                'name'         => 'Jayy',
                'user_id'      => 'KH-0001',
                'phone_number' => '+1 (555) 010-0001',
                'status'       => 'Active',
                'role_name'    => 'Super Admin',
                'avatar'       => 'photo_defaults.jpg',
                'position'     => 'HR Director',
                'department'   => 'Human Resources',
                'line_manager' => 'Self',
                'seconde_line_manager' => 'Board of Directors',
                'updated_at'   => $now,
            ]);
        } else {
            DB::table('users')->insert([
                'id'           => 1,
                'name'         => 'Jayy',
                'user_id'      => 'KH-0001',
                'email'        => 'jaycoab2@gmail.com',
                'join_date'    => 'Mon, Jan 10, 2022 09:00 AM',
                'last_login'   => $now->toDateTimeString(),
                'phone_number' => '+1 (555) 010-0001',
                'status'       => 'Active',
                'role_name'    => 'Super Admin',
                'avatar'       => 'photo_defaults.jpg',
                'position'     => 'HR Director',
                'department'   => 'Human Resources',
                'line_manager' => 'Self',
                'seconde_line_manager' => 'Board of Directors',
                'password'     => $password,
                'created_at'   => $now,
                'updated_at'   => $now,
            ]);
        }

        $mockUsers = [
            [
                'name'         => 'Sarah Jenkins',
                'user_id'      => 'KH-0002',
                'email'        => 'admin@gmail.com',
                'join_date'    => 'Tue, Feb 15, 2022 09:30 AM',
                'phone_number' => '+1 (555) 010-0002',
                'status'       => 'Active',
                'role_name'    => 'Admin',
                'avatar'       => 'photo_defaults.jpg',
                'position'     => 'Manager',
                'department'   => 'IT Management',
                'line_manager' => 'Jayy',
                'seconde_line_manager' => 'Self',
                'gender'       => 'Female',
                'birth_date'   => '1988-04-12',
                'address'      => '742 Evergreen Terrace',
                'state'        => 'California',
                'country'      => 'United States',
                'pin_code'     => '94102',
                'passport_no'  => 'USA-9823412',
                'salary'       => '125000',
                'basic'        => '65000',
                'da'           => '12000',
                'hra'          => '18000',
                'conveyance'   => '5000',
                'allowance'    => '10000',
                'medical_allowance' => '5000',
                'tds'          => '5000',
                'esi'          => '1500',
                'pf'           => '3500',
                'leave'        => '0',
                'prof_tax'     => '500',
                'labour_welfare' => '200',
                'emergency_primary' => 'Robert Jenkins',
                'rel_primary'  => 'Spouse',
                'phone_primary'=> '+1 (555) 010-9902',
                'bank_name'    => 'JPMorgan Chase Bank',
                'bank_account' => '984512039485',
                'ifsc_code'    => 'CHASUS33',
                'pan_no'       => 'PANUS9845K',
            ],
            [
                'name'         => 'Alexander Reed',
                'user_id'      => 'KH-0003',
                'email'        => 'alexander.reed@example.com',
                'join_date'    => 'Wed, Mar 02, 2022 10:00 AM',
                'phone_number' => '+1 (555) 010-0003',
                'status'       => 'Active',
                'role_name'    => 'Employee',
                'avatar'       => 'photo_defaults.jpg',
                'position'     => 'Web Developer',
                'department'   => 'Web Department',
                'line_manager' => 'Sarah Jenkins',
                'seconde_line_manager' => 'Jayy',
                'gender'       => 'Male',
                'birth_date'   => '1992-08-24',
                'address'      => '350 Bay Street, Apt 4B',
                'state'        => 'California',
                'country'      => 'United States',
                'pin_code'     => '94133',
                'passport_no'  => 'USA-4819203',
                'salary'       => '95000',
                'basic'        => '50000',
                'da'           => '9000',
                'hra'          => '14000',
                'conveyance'   => '4000',
                'allowance'    => '8000',
                'medical_allowance' => '4000',
                'tds'          => '3500',
                'esi'          => '1200',
                'pf'           => '2800',
                'leave'        => '0',
                'prof_tax'     => '400',
                'labour_welfare' => '150',
                'emergency_primary' => 'Eleanor Reed',
                'rel_primary'  => 'Mother',
                'phone_primary'=> '+1 (555) 010-9903',
                'bank_name'    => 'Bank of America',
                'bank_account' => '482019482019',
                'ifsc_code'    => 'BOFAUS3N',
                'pan_no'       => 'PANUS4820A',
            ],
            [
                'name'         => 'Elena Rostova',
                'user_id'      => 'KH-0004',
                'email'        => 'elena.rostova@example.com',
                'join_date'    => 'Mon, Apr 18, 2022 09:15 AM',
                'phone_number' => '+1 (555) 010-0004',
                'status'       => 'Active',
                'role_name'    => 'Employee',
                'avatar'       => 'photo_defaults.jpg',
                'position'     => 'Web Designer',
                'department'   => 'Product & UX Design',
                'line_manager' => 'Sarah Jenkins',
                'seconde_line_manager' => 'Jayy',
                'gender'       => 'Female',
                'birth_date'   => '1995-11-03',
                'address'      => '520 Market St, Suite 12',
                'state'        => 'California',
                'country'      => 'United States',
                'pin_code'     => '94105',
                'passport_no'  => 'USA-7734190',
                'salary'       => '92000',
                'basic'        => '48000',
                'da'           => '8500',
                'hra'          => '13500',
                'conveyance'   => '4000',
                'allowance'    => '8000',
                'medical_allowance' => '4000',
                'tds'          => '3200',
                'esi'          => '1100',
                'pf'           => '2700',
                'leave'        => '0',
                'prof_tax'     => '400',
                'labour_welfare' => '150',
                'emergency_primary' => 'Dmitri Rostov',
                'rel_primary'  => 'Father',
                'phone_primary'=> '+1 (555) 010-9904',
                'bank_name'    => 'Wells Fargo Bank',
                'bank_account' => '773918204918',
                'ifsc_code'    => 'WFBIUS6S',
                'pan_no'       => 'PANUS7739R',
            ],
            [
                'name'         => 'Marcus Vance',
                'user_id'      => 'KH-0005',
                'email'        => 'marcus.vance@example.com',
                'join_date'    => 'Thu, Jun 09, 2022 10:30 AM',
                'phone_number' => '+1 (555) 010-0005',
                'status'       => 'Active',
                'role_name'    => 'Employee',
                'avatar'       => 'photo_defaults.jpg',
                'position'     => 'Team Leader',
                'department'   => 'Web Department',
                'line_manager' => 'Sarah Jenkins',
                'seconde_line_manager' => 'Jayy',
                'gender'       => 'Male',
                'birth_date'   => '1987-01-19',
                'address'      => '1250 Folsom St',
                'state'        => 'California',
                'country'      => 'United States',
                'pin_code'     => '94103',
                'passport_no'  => 'USA-3391024',
                'salary'       => '110000',
                'basic'        => '58000',
                'da'           => '10500',
                'hra'          => '16000',
                'conveyance'   => '4500',
                'allowance'    => '9500',
                'medical_allowance' => '4500',
                'tds'          => '4200',
                'esi'          => '1300',
                'pf'           => '3200',
                'leave'        => '0',
                'prof_tax'     => '450',
                'labour_welfare' => '180',
                'emergency_primary' => 'Chloe Vance',
                'rel_primary'  => 'Spouse',
                'phone_primary'=> '+1 (555) 010-9905',
                'bank_name'    => 'Citibank N.A.',
                'bank_account' => '339182740192',
                'ifsc_code'    => 'CITIUS33',
                'pan_no'       => 'PANUS3391M',
            ],
            [
                'name'         => 'Aisha Patel',
                'user_id'      => 'KH-0006',
                'email'        => 'aisha.patel@example.com',
                'join_date'    => 'Mon, Aug 01, 2022 09:00 AM',
                'phone_number' => '+1 (555) 010-0006',
                'status'       => 'Active',
                'role_name'    => 'Employee',
                'avatar'       => 'photo_defaults.jpg',
                'position'     => 'Android Developer',
                'department'   => 'IT Management',
                'line_manager' => 'Marcus Vance',
                'seconde_line_manager' => 'Sarah Jenkins',
                'gender'       => 'Female',
                'birth_date'   => '1993-06-15',
                'address'      => '880 Mission St, Apt 15C',
                'state'        => 'California',
                'country'      => 'United States',
                'pin_code'     => '94103',
                'passport_no'  => 'USA-5510924',
                'salary'       => '96000',
                'basic'        => '51000',
                'da'           => '9200',
                'hra'          => '14200',
                'conveyance'   => '4000',
                'allowance'    => '8200',
                'medical_allowance' => '4000',
                'tds'          => '3600',
                'esi'          => '1200',
                'pf'           => '2800',
                'leave'        => '0',
                'prof_tax'     => '400',
                'labour_welfare' => '150',
                'emergency_primary' => 'Dev Patel',
                'rel_primary'  => 'Brother',
                'phone_primary'=> '+1 (555) 010-9906',
                'bank_name'    => 'PNC Bank',
                'bank_account' => '551029384756',
                'ifsc_code'    => 'PNCCUS33',
                'pan_no'       => 'PANUS5510P',
            ],
            [
                'name'         => 'Lucas Moreau',
                'user_id'      => 'KH-0007',
                'email'        => 'lucas.moreau@example.com',
                'join_date'    => 'Fri, Sep 16, 2022 10:00 AM',
                'phone_number' => '+1 (555) 010-0007',
                'status'       => 'Active',
                'role_name'    => 'Employee',
                'avatar'       => 'photo_defaults.jpg',
                'position'     => 'IOS Developer',
                'department'   => 'IT Management',
                'line_manager' => 'Marcus Vance',
                'seconde_line_manager' => 'Sarah Jenkins',
                'gender'       => 'Male',
                'birth_date'   => '1994-09-28',
                'address'      => '420 Montgomery St',
                'state'        => 'California',
                'country'      => 'United States',
                'pin_code'     => '94104',
                'passport_no'  => 'USA-6629183',
                'salary'       => '98000',
                'basic'        => '52000',
                'da'           => '9500',
                'hra'          => '14500',
                'conveyance'   => '4000',
                'allowance'    => '8500',
                'medical_allowance' => '4000',
                'tds'          => '3700',
                'esi'          => '1250',
                'pf'           => '2900',
                'leave'        => '0',
                'prof_tax'     => '400',
                'labour_welfare' => '160',
                'emergency_primary' => 'Sophie Moreau',
                'rel_primary'  => 'Sister',
                'phone_primary'=> '+1 (555) 010-9907',
                'bank_name'    => 'Capital One',
                'bank_account' => '662910482736',
                'ifsc_code'    => 'NFBKUS33',
                'pan_no'       => 'PANUS6629M',
            ],
            [
                'name'         => 'Emily Chen',
                'user_id'      => 'KH-0008',
                'email'        => 'emily.chen@example.com',
                'join_date'    => 'Mon, Nov 07, 2022 09:00 AM',
                'phone_number' => '+1 (555) 010-0008',
                'status'       => 'Active',
                'role_name'    => 'Employee',
                'avatar'       => 'photo_defaults.jpg',
                'position'     => 'Manager',
                'department'   => 'Marketing',
                'line_manager' => 'Jayy',
                'seconde_line_manager' => 'Self',
                'gender'       => 'Female',
                'birth_date'   => '1990-03-21',
                'address'      => '150 California St, 18th Floor',
                'state'        => 'California',
                'country'      => 'United States',
                'pin_code'     => '94111',
                'passport_no'  => 'USA-8829103',
                'salary'       => '105000',
                'basic'        => '55000',
                'da'           => '10000',
                'hra'          => '15500',
                'conveyance'   => '4500',
                'allowance'    => '9000',
                'medical_allowance' => '4500',
                'tds'          => '4000',
                'esi'          => '1300',
                'pf'           => '3100',
                'leave'        => '0',
                'prof_tax'     => '450',
                'labour_welfare' => '170',
                'emergency_primary' => 'Wei Chen',
                'rel_primary'  => 'Father',
                'phone_primary'=> '+1 (555) 010-9908',
                'bank_name'    => 'U.S. Bank',
                'bank_account' => '882910482910',
                'ifsc_code'    => 'USBKUS44',
                'pan_no'       => 'PANUS8829C',
            ],
            [
                'name'         => 'David Miller',
                'user_id'      => 'KH-0009',
                'email'        => 'david.miller@example.com',
                'join_date'    => 'Wed, Jan 11, 2023 09:30 AM',
                'phone_number' => '+1 (555) 010-0009',
                'status'       => 'Active',
                'role_name'    => 'Employee',
                'avatar'       => 'photo_defaults.jpg',
                'position'     => 'CFO',
                'department'   => 'Finance & Accounting',
                'line_manager' => 'Jayy',
                'seconde_line_manager' => 'Board of Directors',
                'gender'       => 'Male',
                'birth_date'   => '1982-12-05',
                'address'      => '600 Pine St, Suite 300',
                'state'        => 'California',
                'country'      => 'United States',
                'pin_code'     => '94108',
                'passport_no'  => 'USA-1102938',
                'salary'       => '140000',
                'basic'        => '72000',
                'da'           => '13000',
                'hra'          => '20000',
                'conveyance'   => '5000',
                'allowance'    => '12000',
                'medical_allowance' => '5000',
                'tds'          => '6000',
                'esi'          => '1600',
                'pf'           => '4000',
                'leave'        => '0',
                'prof_tax'     => '500',
                'labour_welfare' => '220',
                'emergency_primary' => 'Katherine Miller',
                'rel_primary'  => 'Spouse',
                'phone_primary'=> '+1 (555) 010-9909',
                'bank_name'    => 'Morgan Stanley Private Bank',
                'bank_account' => '110293847561',
                'ifsc_code'    => 'MSPBUS33',
                'pan_no'       => 'PANUS1102M',
            ],
            [
                'name'         => 'Hannah Schmidt',
                'user_id'      => 'KH-0010',
                'email'        => 'hannah.schmidt@example.com',
                'join_date'    => 'Tue, Mar 14, 2023 10:00 AM',
                'phone_number' => '+1 (555) 010-0010',
                'status'       => 'Active',
                'role_name'    => 'Normal User',
                'avatar'       => 'photo_defaults.jpg',
                'position'     => 'Web Developer',
                'department'   => 'Web Department',
                'line_manager' => 'Marcus Vance',
                'seconde_line_manager' => 'Sarah Jenkins',
                'gender'       => 'Female',
                'birth_date'   => '1996-07-18',
                'address'      => '210 Post St',
                'state'        => 'California',
                'country'      => 'United States',
                'pin_code'     => '94108',
                'passport_no'  => 'USA-4491028',
                'salary'       => '88000',
                'basic'        => '46000',
                'da'           => '8000',
                'hra'          => '13000',
                'conveyance'   => '4000',
                'allowance'    => '7500',
                'medical_allowance' => '4000',
                'tds'          => '3000',
                'esi'          => '1100',
                'pf'           => '2600',
                'leave'        => '0',
                'prof_tax'     => '400',
                'labour_welfare' => '140',
                'emergency_primary' => 'Klaus Schmidt',
                'rel_primary'  => 'Father',
                'phone_primary'=> '+1 (555) 010-9910',
                'bank_name'    => 'TD Bank',
                'bank_account' => '449102938475',
                'ifsc_code'    => 'NRTHUS33',
                'pan_no'       => 'PANUS4491S',
            ],
            [
                'name'         => 'Jordan Taylor',
                'user_id'      => 'KH-0011',
                'email'        => 'jordan.taylor@example.com',
                'join_date'    => 'Thu, May 25, 2023 09:00 AM',
                'phone_number' => '+1 (555) 010-0011',
                'status'       => 'Active',
                'role_name'    => 'Employee',
                'avatar'       => 'photo_defaults.jpg',
                'position'     => 'Team Leader',
                'department'   => 'Marketing',
                'line_manager' => 'Emily Chen',
                'seconde_line_manager' => 'Jayy',
                'gender'       => 'Male',
                'birth_date'   => '1991-10-30',
                'address'      => '700 Kearny St',
                'state'        => 'California',
                'country'      => 'United States',
                'pin_code'     => '94108',
                'passport_no'  => 'USA-9938201',
                'salary'       => '94000',
                'basic'        => '49000',
                'da'           => '8800',
                'hra'          => '13800',
                'conveyance'   => '4000',
                'allowance'    => '8000',
                'medical_allowance' => '4000',
                'tds'          => '3400',
                'esi'          => '1200',
                'pf'           => '2750',
                'leave'        => '0',
                'prof_tax'     => '400',
                'labour_welfare' => '150',
                'emergency_primary' => 'Morgan Taylor',
                'rel_primary'  => 'Partner',
                'phone_primary'=> '+1 (555) 010-9911',
                'bank_name'    => 'PNC Bank',
                'bank_account' => '993820194820',
                'ifsc_code'    => 'PNCCUS33',
                'pan_no'       => 'PANUS9938T',
            ],
            [
                'name'         => 'Global Acme Corp (Acme Ltd)',
                'user_id'      => 'KH-0012',
                'email'        => 'billing@acmecorp.com',
                'join_date'    => 'Fri, Jun 30, 2023 11:00 AM',
                'phone_number' => '+1 (555) 010-0012',
                'status'       => 'Active',
                'role_name'    => 'Client',
                'avatar'       => 'photo_defaults.jpg',
                'position'     => 'CEO',
                'department'   => 'Sales & Business Development',
                'line_manager' => 'Jayy',
                'seconde_line_manager' => 'David Miller',
                'gender'       => 'Male',
                'birth_date'   => '1979-05-14',
                'address'      => '100 Enterprise Way, Suite 800',
                'state'        => 'New York',
                'country'      => 'United States',
                'pin_code'     => '10001',
                'passport_no'  => 'USA-2201928',
                'salary'       => '150000',
                'basic'        => '80000',
                'da'           => '14000',
                'hra'          => '22000',
                'conveyance'   => '5000',
                'allowance'    => '13000',
                'medical_allowance' => '5000',
                'tds'          => '7000',
                'esi'          => '1800',
                'pf'           => '4500',
                'leave'        => '0',
                'prof_tax'     => '500',
                'labour_welfare' => '250',
                'emergency_primary' => 'Corporate Legal Team',
                'rel_primary'  => 'Attorney',
                'phone_primary'=> '+1 (555) 010-9912',
                'bank_name'    => 'Goldman Sachs Bank',
                'bank_account' => '220192847192',
                'ifsc_code'    => 'GSBDUS33',
                'pan_no'       => 'PANUS2201A',
            ],
        ];

        // Seed Users
        foreach ($mockUsers as $u) {
            DB::table('users')->updateOrInsert(
                ['user_id' => $u['user_id']],
                [
                    'name'         => $u['name'],
                    'email'        => $u['email'],
                    'join_date'    => $u['join_date'],
                    'last_login'   => $now->subDays(rand(0, 10))->toDateTimeString(),
                    'phone_number' => $u['phone_number'],
                    'status'       => $u['status'],
                    'role_name'    => $u['role_name'],
                    'avatar'       => $u['avatar'],
                    'position'     => $u['position'],
                    'department'   => $u['department'],
                    'line_manager' => $u['line_manager'],
                    'seconde_line_manager' => $u['seconde_line_manager'],
                    'password'     => $password,
                    'created_at'   => $now,
                    'updated_at'   => $now,
                ]
            );
        }

        // Also add Jayy into the employee profile array
        $allProfileEmployees = array_merge([
            [
                'name'         => 'Jayy',
                'user_id'      => 'KH-0001',
                'email'        => 'jaycoab2@gmail.com',
                'join_date'    => 'Mon, Jan 10, 2022 09:00 AM',
                'phone_number' => '+1 (555) 010-0001',
                'position'     => 'HR Director',
                'department'   => 'Human Resources',
                'line_manager' => 'Self',
                'gender'       => 'Male',
                'birth_date'   => '1985-02-14',
                'address'      => '100 Innovation Boulevard, Penthouse 1',
                'state'        => 'California',
                'country'      => 'United States',
                'pin_code'     => '94107',
                'passport_no'  => 'USA-1029384',
                'salary'       => '135000',
                'basic'        => '70000',
                'da'           => '12500',
                'hra'          => '19000',
                'conveyance'   => '5000',
                'allowance'    => '11500',
                'medical_allowance' => '5000',
                'tds'          => '5500',
                'esi'          => '1500',
                'pf'           => '3800',
                'leave'        => '0',
                'prof_tax'     => '500',
                'labour_welfare' => '200',
                'emergency_primary' => 'Jessica Jay',
                'rel_primary'  => 'Spouse',
                'phone_primary'=> '+1 (555) 010-9901',
                'bank_name'    => 'Silicon Valley Bank',
                'bank_account' => '102938475629',
                'ifsc_code'    => 'SVBUS33',
                'pan_no'       => 'PANUS1029J',
            ]
        ], $mockUsers);

        $moduleNames = [
            'Holidays',
            'Leaves',
            'Clients',
            'Projects',
            'Tasks',
            'Chats',
            'Assets',
            'Timing Sheets'
        ];

        foreach ($allProfileEmployees as $emp) {
            // Employees table (for all/employee/card & list)
            DB::table('employees')->updateOrInsert(
                ['employee_id' => $emp['user_id']],
                [
                    'name'         => $emp['name'],
                    'email'        => $emp['email'],
                    'birth_date'   => $emp['birth_date'],
                    'gender'       => $emp['gender'],
                    'employee_id'  => $emp['user_id'],
                    'line_manager' => $emp['line_manager'],
                    'created_at'   => $now,
                    'updated_at'   => $now,
                ]
            );

            // Profile Information
            DB::table('profile_information')->updateOrInsert(
                ['user_id' => $emp['user_id']],
                [
                    'name'         => $emp['name'],
                    'user_id'      => $emp['user_id'],
                    'email'        => $emp['email'],
                    'birth_date'   => $emp['birth_date'],
                    'gender'       => $emp['gender'],
                    'address'      => $emp['address'],
                    'state'        => $emp['state'],
                    'country'      => $emp['country'],
                    'pin_code'     => $emp['pin_code'],
                    'phone_number' => $emp['phone_number'],
                    'department'   => $emp['department'],
                    'designation'  => $emp['position'],
                    'reports_to'   => $emp['line_manager'],
                    'created_at'   => $now,
                    'updated_at'   => $now,
                ]
            );

            // Personal Information
            DB::table('personal_information')->updateOrInsert(
                ['user_id' => $emp['user_id']],
                [
                    'user_id'              => $emp['user_id'],
                    'passport_no'          => $emp['passport_no'],
                    'passport_expiry_date' => '2032-12-31',
                    'tel'                  => $emp['phone_number'],
                    'nationality'          => 'American',
                    'religion'             => 'Christian',
                    'marital_status'       => 'Married',
                    'employment_of_spouse' => 'Yes',
                    'children'             => '2',
                    'created_at'           => $now,
                    'updated_at'           => $now,
                ]
            );

            // Emergency Contacts
            DB::table('user_emergency_contacts')->updateOrInsert(
                ['user_id' => $emp['user_id']],
                [
                    'user_id'                => $emp['user_id'],
                    'name_primary'           => $emp['emergency_primary'],
                    'relationship_primary'   => $emp['rel_primary'],
                    'phone_primary'          => $emp['phone_primary'],
                    'phone_2_primary'        => '+1 (555) 010-9999',
                    'name_secondary'         => 'Emergency Dispatch Service',
                    'relationship_secondary' => 'Service',
                    'phone_secondary'        => '+1 (800) 555-0199',
                    'phone_2_secondary'      => null,
                    'created_at'             => $now,
                    'updated_at'             => $now,
                ]
            );

            // Bank Information
            DB::table('bank_information')->updateOrInsert(
                ['user_id' => $emp['user_id']],
                [
                    'user_id'         => $emp['user_id'],
                    'bank_name'       => $emp['bank_name'],
                    'bank_account_no' => $emp['bank_account'],
                    'ifsc_code'       => $emp['ifsc_code'],
                    'pan_no'          => $emp['pan_no'],
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ]
            );

            // Staff Salaries (Payroll)
            DB::table('staff_salaries')->updateOrInsert(
                ['user_id' => $emp['user_id']],
                [
                    'name'              => $emp['name'],
                    'user_id'           => $emp['user_id'],
                    'salary'            => $emp['salary'],
                    'basic'             => $emp['basic'],
                    'da'                => $emp['da'],
                    'hra'               => $emp['hra'],
                    'conveyance'        => $emp['conveyance'],
                    'allowance'         => $emp['allowance'],
                    'medical_allowance' => $emp['medical_allowance'],
                    'tds'               => $emp['tds'],
                    'esi'               => $emp['esi'],
                    'pf'                => $emp['pf'],
                    'leave'             => $emp['leave'],
                    'prof_tax'          => $emp['prof_tax'],
                    'labour_welfare'    => $emp['labour_welfare'],
                    'created_at'        => $now,
                    'updated_at'        => $now,
                ]
            );

            // Module Permissions
            if (!DB::table('module_permissions')->where('employee_id', $emp['user_id'])->exists()) {
                foreach ($moduleNames as $idx => $modName) {
                    DB::table('module_permissions')->insert([
                        'employee_id'       => $emp['user_id'],
                        'module_permission' => $modName,
                        'id_count'          => (string)($idx + 1),
                        'read'              => 'Y',
                        'write'             => 'Y',
                        'create'            => 'Y',
                        'delete'            => in_array($emp['user_id'], ['KH-0001', 'KH-0002']) ? 'Y' : 'N',
                        'import'            => 'Y',
                        'export'            => in_array($emp['user_id'], ['KH-0001', 'KH-0002']) ? 'Y' : 'N',
                        'created_at'        => $now,
                        'updated_at'        => $now,
                    ]);
                }
            }
        }

        // 5. Holidays
        $holidays = [
            ['name_holiday' => "New Year's Day",         'date_holiday' => '2026-01-01'],
            ['name_holiday' => 'Martin Luther King Jr. Day', 'date_holiday' => '2026-01-19'],
            ['name_holiday' => "Presidents' Day",        'date_holiday' => '2026-02-16'],
            ['name_holiday' => 'Memorial Day',           'date_holiday' => '2026-05-25'],
            ['name_holiday' => 'Juneteenth National Day', 'date_holiday' => '2026-06-19'],
            ['name_holiday' => 'Independence Day',       'date_holiday' => '2026-07-04'],
            ['name_holiday' => 'Labor Day',              'date_holiday' => '2026-09-07'],
            ['name_holiday' => 'Apex Annual Summit Day', 'date_holiday' => '2026-10-15'],
            ['name_holiday' => 'Veterans Day',           'date_holiday' => '2026-11-11'],
            ['name_holiday' => 'Thanksgiving Day',       'date_holiday' => '2026-11-26'],
            ['name_holiday' => 'Christmas Day',          'date_holiday' => '2026-12-25'],
        ];
        foreach ($holidays as $h) {
            DB::table('holidays')->updateOrInsert(
                ['name_holiday' => $h['name_holiday']],
                [
                    'date_holiday' => $h['date_holiday'],
                    'created_at'   => $now,
                    'updated_at'   => $now,
                ]
            );
        }

        // 6. Leaves (Admin & Employee)
        $leaveEntries = [
            [
                'staff_id'        => 'KH-0001',
                'employee_name'   => 'Jayy',
                'leave_type'      => 'Annual Leave',
                'remaining_leave' => '12',
                'date_from'       => '2026-09-15',
                'date_to'         => '2026-09-18',
                'leave_date'      => json_encode(['2026-09-15', '2026-09-16', '2026-09-17', '2026-09-18']),
                'leave_day'       => json_encode(['Full Day', 'Full Day', 'Full Day', 'Full Day']),
                'number_of_day'   => '4',
                'reason'          => 'Annual family vacation retreat.',
                'approved_by'     => 'Board of Directors',
                'status'          => 'Approved',
            ],
            [
                'staff_id'        => 'KH-0001',
                'employee_name'   => 'Jayy',
                'leave_type'      => 'Casual Leave',
                'remaining_leave' => '10',
                'date_from'       => '2026-10-02',
                'date_to'         => '2026-10-02',
                'leave_date'      => json_encode(['2026-10-02']),
                'leave_day'       => json_encode(['Full Day']),
                'number_of_day'   => '1',
                'reason'          => 'Personal administrative errands.',
                'approved_by'     => 'Board of Directors',
                'status'          => 'Pending',
            ],
            [
                'staff_id'        => 'KH-0003',
                'employee_name'   => 'Alexander Reed',
                'leave_type'      => 'Medical Leave',
                'remaining_leave' => '3',
                'date_from'       => '2026-08-10',
                'date_to'         => '2026-08-11',
                'leave_date'      => json_encode(['2026-08-10', '2026-08-11']),
                'leave_day'       => json_encode(['Full Day', 'Full Day']),
                'number_of_day'   => '2',
                'reason'          => 'Dental surgery and prescribed recovery.',
                'approved_by'     => 'Sarah Jenkins',
                'status'          => 'Approved',
            ],
            [
                'staff_id'        => 'KH-0004',
                'employee_name'   => 'Elena Rostova',
                'leave_type'      => 'Casual Leave',
                'remaining_leave' => '6',
                'date_from'       => '2026-09-22',
                'date_to'         => '2026-09-23',
                'leave_date'      => json_encode(['2026-09-22', '2026-09-23']),
                'leave_day'       => json_encode(['Full Day', 'Full Day']),
                'number_of_day'   => '2',
                'reason'          => 'Attending Figma Config conference in San Francisco.',
                'approved_by'     => 'Sarah Jenkins',
                'status'          => 'Approved',
            ],
            [
                'staff_id'        => 'KH-0005',
                'employee_name'   => 'Marcus Vance',
                'leave_type'      => 'Sick Leave',
                'remaining_leave' => '4',
                'date_from'       => '2026-07-14',
                'date_to'         => '2026-07-15',
                'leave_date'      => json_encode(['2026-07-14', '2026-07-15']),
                'leave_day'       => json_encode(['Full Day', 'Full Day']),
                'number_of_day'   => '2',
                'reason'          => 'Seasonal flu symptoms.',
                'approved_by'     => 'Sarah Jenkins',
                'status'          => 'Approved',
            ],
            [
                'staff_id'        => 'KH-0006',
                'employee_name'   => 'Aisha Patel',
                'leave_type'      => 'Annual Leave',
                'remaining_leave' => '9',
                'date_from'       => '2026-11-02',
                'date_to'         => '2026-11-06',
                'leave_date'      => json_encode(['2026-11-02', '2026-11-03', '2026-11-04', '2026-11-05', '2026-11-06']),
                'leave_day'       => json_encode(['Full Day', 'Full Day', 'Full Day', 'Full Day', 'Full Day']),
                'number_of_day'   => '5',
                'reason'          => 'Diwali festival family celebration.',
                'approved_by'     => 'Marcus Vance',
                'status'          => 'Pending',
            ],
            [
                'staff_id'        => 'KH-0007',
                'employee_name'   => 'Lucas Moreau',
                'leave_type'      => 'Medical Leave',
                'remaining_leave' => '2',
                'date_from'       => '2026-08-28',
                'date_to'         => '2026-08-29',
                'leave_date'      => json_encode(['2026-08-28', '2026-08-29']),
                'leave_day'       => json_encode(['Full Day', 'Full Day']),
                'number_of_day'   => '2',
                'reason'          => 'Physiotherapy rehabilitation appointment.',
                'approved_by'     => 'Marcus Vance',
                'status'          => 'Approved',
            ],
            [
                'staff_id'        => 'KH-0008',
                'employee_name'   => 'Emily Chen',
                'leave_type'      => 'Casual Leave',
                'remaining_leave' => '5',
                'date_from'       => '2026-09-30',
                'date_to'         => '2026-10-01',
                'leave_date'      => json_encode(['2026-09-30', '2026-10-01']),
                'leave_day'       => json_encode(['Full Day', 'Full Day']),
                'number_of_day'   => '2',
                'reason'          => 'House relocation and setup.',
                'approved_by'     => 'Jayy',
                'status'          => 'Approved',
            ],
            [
                'staff_id'        => 'KH-0010',
                'employee_name'   => 'Hannah Schmidt',
                'leave_type'      => 'Sick Leave',
                'remaining_leave' => '5',
                'date_from'       => '2026-09-08',
                'date_to'         => '2026-09-09',
                'leave_date'      => json_encode(['2026-09-08', '2026-09-09']),
                'leave_day'       => json_encode(['Full Day', 'Full Day']),
                'number_of_day'   => '2',
                'reason'          => 'Severe migraine episode.',
                'approved_by'     => 'Marcus Vance',
                'status'          => 'Pending',
            ],
            [
                'staff_id'        => 'KH-0011',
                'employee_name'   => 'Jordan Taylor',
                'leave_type'      => 'Annual Leave',
                'remaining_leave' => '8',
                'date_from'       => '2026-06-15',
                'date_to'         => '2026-06-19',
                'leave_date'      => json_encode(['2026-06-15', '2026-06-16', '2026-06-17', '2026-06-18', '2026-06-19']),
                'leave_day'       => json_encode(['Full Day', 'Full Day', 'Full Day', 'Full Day', 'Full Day']),
                'number_of_day'   => '5',
                'reason'          => 'Summer road trip camping.',
                'approved_by'     => 'Emily Chen',
                'status'          => 'Declined',
            ],
        ];

        DB::table('leaves')->truncate();
        foreach ($leaveEntries as $lv) {
            DB::table('leaves')->insert(array_merge($lv, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

        // 7. Performance Indicators & Appraisals
        DB::table('performance_indicators')->truncate();
        $indicators = [
            [
                'user_id'                  => 'KH-0003',
                'designation'              => 'Web Developer',
                'customer_eperience'       => 'Advanced',
                'marketing'                => 'Intermediate',
                'management'               => 'Intermediate',
                'administration'           => 'Beginner',
                'presentation_skill'       => 'Advanced',
                'quality_of_Work'          => 'Expert / Leader',
                'efficiency'               => 'Expert / Leader',
                'integrity'                => 'Expert / Leader',
                'professionalism'          => 'Expert / Leader',
                'team_work'                => 'Advanced',
                'critical_thinking'        => 'Expert / Leader',
                'conflict_management'      => 'Intermediate',
                'attendance'               => 'Expert / Leader',
                'ability_to_meet_deadline' => 'Expert / Leader',
                'status'                   => 'Active',
            ],
            [
                'user_id'                  => 'KH-0004',
                'designation'              => 'Web Designer',
                'customer_eperience'       => 'Expert / Leader',
                'marketing'                => 'Advanced',
                'management'               => 'Intermediate',
                'administration'           => 'Intermediate',
                'presentation_skill'       => 'Expert / Leader',
                'quality_of_Work'          => 'Expert / Leader',
                'efficiency'               => 'Advanced',
                'integrity'                => 'Expert / Leader',
                'professionalism'          => 'Expert / Leader',
                'team_work'                => 'Advanced',
                'critical_thinking'        => 'Advanced',
                'conflict_management'      => 'Intermediate',
                'attendance'               => 'Advanced',
                'ability_to_meet_deadline' => 'Expert / Leader',
                'status'                   => 'Active',
            ],
            [
                'user_id'                  => 'KH-0005',
                'designation'              => 'Team Leader',
                'customer_eperience'       => 'Advanced',
                'marketing'                => 'Advanced',
                'management'               => 'Expert / Leader',
                'administration'           => 'Advanced',
                'presentation_skill'       => 'Expert / Leader',
                'quality_of_Work'          => 'Expert / Leader',
                'efficiency'               => 'Expert / Leader',
                'integrity'                => 'Expert / Leader',
                'professionalism'          => 'Expert / Leader',
                'team_work'                => 'Expert / Leader',
                'critical_thinking'        => 'Expert / Leader',
                'conflict_management'      => 'Expert / Leader',
                'attendance'               => 'Expert / Leader',
                'ability_to_meet_deadline' => 'Expert / Leader',
                'status'                   => 'Active',
            ],
            [
                'user_id'                  => 'KH-0008',
                'designation'              => 'Manager',
                'customer_eperience'       => 'Expert / Leader',
                'marketing'                => 'Expert / Leader',
                'management'               => 'Expert / Leader',
                'administration'           => 'Advanced',
                'presentation_skill'       => 'Expert / Leader',
                'quality_of_Work'          => 'Advanced',
                'efficiency'               => 'Advanced',
                'integrity'                => 'Expert / Leader',
                'professionalism'          => 'Expert / Leader',
                'team_work'                => 'Expert / Leader',
                'critical_thinking'        => 'Expert / Leader',
                'conflict_management'      => 'Advanced',
                'attendance'               => 'Advanced',
                'ability_to_meet_deadline' => 'Expert / Leader',
                'status'                   => 'Active',
            ],
        ];
        foreach ($indicators as $ind) {
            DB::table('performance_indicators')->insert(array_merge($ind, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

        DB::table('performance_appraisals')->truncate();
        $appraisals = [
            [
                'name'                     => 'Alexander Reed',
                'date'                     => '2026-08-30',
                'user_id'                  => 'KH-0003',
                'customer_experience'      => 'Advanced',
                'marketing'                => 'Intermediate',
                'management'               => 'Intermediate',
                'administration'           => 'Beginner',
                'presentation_skill'       => 'Advanced',
                'quality_of_Work'          => 'Expert / Leader',
                'efficiency'               => 'Expert / Leader',
                'integrity'                => 'Expert / Leader',
                'professionalism'          => 'Expert / Leader',
                'team_work'                => 'Advanced',
                'critical_thinking'        => 'Expert / Leader',
                'conflict_management'      => 'Intermediate',
                'attendance'               => 'Expert / Leader',
                'ability_to_meet_deadline' => 'Expert / Leader',
                'status'                   => 'Active',
            ],
            [
                'name'                     => 'Elena Rostova',
                'date'                     => '2026-08-31',
                'user_id'                  => 'KH-0004',
                'customer_experience'      => 'Expert / Leader',
                'marketing'                => 'Advanced',
                'management'               => 'Intermediate',
                'administration'           => 'Intermediate',
                'presentation_skill'       => 'Expert / Leader',
                'quality_of_Work'          => 'Expert / Leader',
                'efficiency'               => 'Advanced',
                'integrity'                => 'Expert / Leader',
                'professionalism'          => 'Expert / Leader',
                'team_work'                => 'Advanced',
                'critical_thinking'        => 'Advanced',
                'conflict_management'      => 'Intermediate',
                'attendance'               => 'Advanced',
                'ability_to_meet_deadline' => 'Expert / Leader',
                'status'                   => 'Active',
            ],
            [
                'name'                     => 'Marcus Vance',
                'date'                     => '2026-09-01',
                'user_id'                  => 'KH-0005',
                'customer_experience'      => 'Advanced',
                'marketing'                => 'Advanced',
                'management'               => 'Expert / Leader',
                'administration'           => 'Advanced',
                'presentation_skill'       => 'Expert / Leader',
                'quality_of_Work'          => 'Expert / Leader',
                'efficiency'               => 'Expert / Leader',
                'integrity'                => 'Expert / Leader',
                'professionalism'          => 'Expert / Leader',
                'team_work'                => 'Expert / Leader',
                'critical_thinking'        => 'Expert / Leader',
                'conflict_management'      => 'Expert / Leader',
                'attendance'               => 'Expert / Leader',
                'ability_to_meet_deadline' => 'Expert / Leader',
                'status'                   => 'Active',
            ],
        ];
        foreach ($appraisals as $app) {
            DB::table('performance_appraisals')->insert(array_merge($app, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

        // 8. Training Types, Trainers & Trainings
        DB::table('training_types')->truncate();
        $trainTypes = [
            ['type' => 'Full-Stack Web Development', 'description' => 'Modern Laravel 13, Vue.js, and API architecture training.', 'status' => 'Active'],
            ['type' => 'Cloud & DevOps Engineering', 'description' => 'AWS infrastructure, Docker containers, and CI/CD pipelines.', 'status' => 'Active'],
            ['type' => 'Leadership & Team Management', 'description' => 'Effective delegation, conflict resolution, and agile leadership.', 'status' => 'Active'],
            ['type' => 'UI/UX Design Systems',       'description' => 'Figma tokens, accessibility (WCAG 2.1), and design consistency.', 'status' => 'Active'],
            ['type' => 'Cybersecurity & Compliance', 'description' => 'Data privacy, OWASP Top 10 mitigation, and corporate infosec.', 'status' => 'Active'],
        ];
        foreach ($trainTypes as $tt) {
            DB::table('training_types')->insert(array_merge($tt, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

        DB::table('trainers')->truncate();
        $trainers = [
            [
                'full_name'   => 'Dr. Marcus Vance',
                'trainer_id'  => 'KH-0005',
                'role'        => 'Lead Systems Architect',
                'email'       => 'marcus.vance@example.com',
                'phone'       => '+1 (555) 010-0005',
                'status'      => 'Active',
                'description' => 'Senior tech lead specializing in scalable distributed architectures.',
            ],
            [
                'full_name'   => 'Elena Rostova',
                'trainer_id'  => 'KH-0004',
                'role'        => 'Design Systems Lead',
                'email'       => 'elena.rostova@example.com',
                'phone'       => '+1 (555) 010-0004',
                'status'      => 'Active',
                'description' => 'Product designer certified in human-computer interaction and design systems.',
            ],
            [
                'full_name'   => 'Sarah Jenkins',
                'trainer_id'  => 'KH-0002',
                'role'        => 'Agile Management Coach',
                'email'       => 'admin@gmail.com',
                'phone'       => '+1 (555) 010-0002',
                'status'      => 'Active',
                'description' => 'Certified Scrum Master with 12 years executive coaching experience.',
            ],
        ];
        foreach ($trainers as $tr) {
            DB::table('trainers')->insert(array_merge($tr, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

        DB::table('trainings')->truncate();
        $trainings = [
            [
                'trainer_id'    => 'KH-0005',
                'employees_id'  => 'KH-0003',
                'training_type' => 'Full-Stack Web Development',
                'trainer'       => 'Dr. Marcus Vance',
                'employees'     => 'Alexander Reed',
                'training_cost' => '$1,200',
                'start_date'    => '2026-09-01',
                'end_date'      => '2026-09-20',
                'description'   => 'Deep-dive masterclass on Laravel queue optimizations and microservices.',
                'status'        => 'Active',
            ],
            [
                'trainer_id'    => 'KH-0004',
                'employees_id'  => 'KH-0010',
                'training_type' => 'UI/UX Design Systems',
                'trainer'       => 'Elena Rostova',
                'employees'     => 'Hannah Schmidt',
                'training_cost' => '$850',
                'start_date'    => '2026-09-10',
                'end_date'      => '2026-09-25',
                'description'   => 'Bridging design tokens and component libraries in responsive web interfaces.',
                'status'        => 'Active',
            ],
            [
                'trainer_id'    => 'KH-0002',
                'employees_id'  => 'KH-0011',
                'training_type' => 'Leadership & Team Management',
                'trainer'       => 'Sarah Jenkins',
                'employees'     => 'Jordan Taylor',
                'training_cost' => '$1,500',
                'start_date'    => '2026-08-05',
                'end_date'      => '2026-08-26',
                'description'   => 'Sprint planning, stakeholder communication, and performance management.',
                'status'        => 'Completed',
            ],
        ];
        foreach ($trainings as $tn) {
            DB::table('trainings')->insert(array_merge($tn, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

        // 9. Estimates and Estimates Additions (Sales)
        DB::table('estimates')->truncate();
        DB::table('estimates_adds')->truncate();
        $estimates = [
            [
                'estimate_number'   => 'EST_0001',
                'client'            => 'Global Acme Corp (Acme Ltd)',
                'project'           => 'Enterprise Cloud ERP Portal',
                'email'             => 'billing@acmecorp.com',
                'tax'               => '10',
                'client_address'    => '100 Enterprise Way, Suite 800, New York, NY',
                'billing_address'   => '100 Enterprise Way, Suite 800, New York, NY',
                'estimate_date'     => '2026-08-15',
                'expiry_date'       => '2026-10-15',
                'total'             => '45000',
                'tax_1'             => '4500',
                'discount'          => '2000',
                'grand_total'       => '47500',
                'other_information' => 'Includes 6 months post-launch dedicated maintenance and SLA.',
                'items'             => [
                    ['item' => 'Backend API Development', 'description' => 'RESTful microservices in Laravel with JWT security.', 'unit_cost' => '15000', 'qty' => '1', 'amount' => '15000'],
                    ['item' => 'Frontend React Dashboard', 'description' => 'Responsive admin analytics panels and real-time graphs.', 'unit_cost' => '18000', 'qty' => '1', 'amount' => '18000'],
                    ['item' => 'DevOps Cloud Setup',      'description' => 'AWS ECS, RDS PostgreSQL, Auto-scaling clusters.', 'unit_cost' => '12000', 'qty' => '1', 'amount' => '12000'],
                ]
            ],
            [
                'estimate_number'   => 'EST_0002',
                'client'            => 'Finovate Capital Partners',
                'project'           => 'Fintech Mobile Banking App',
                'email'             => 'accounts@finovatecap.com',
                'tax'               => '8',
                'client_address'    => '500 Wall Street, Floor 22, New York, NY',
                'billing_address'   => '500 Wall Street, Floor 22, New York, NY',
                'estimate_date'     => '2026-08-20',
                'expiry_date'       => '2026-10-20',
                'total'             => '32000',
                'tax_1'             => '2560',
                'discount'          => '1500',
                'grand_total'       => '33060',
                'other_information' => 'Compliant with PCI-DSS Level 1 specifications and end-to-end encryption.',
                'items'             => [
                    ['item' => 'iOS App Native Build',     'description' => 'SwiftUI financial dashboard with biometrics authentication.', 'unit_cost' => '16000', 'qty' => '1', 'amount' => '16000'],
                    ['item' => 'Android App Native Build', 'description' => 'Kotlin native application with secure enclave storage.', 'unit_cost' => '16000', 'qty' => '1', 'amount' => '16000'],
                ]
            ],
            [
                'estimate_number'   => 'EST_0003',
                'client'            => 'OmniMedia Publishing Group',
                'project'           => 'High-Traffic Digital Publishing Platform',
                'email'             => 'ops@omnimediagroup.com',
                'tax'               => '5',
                'client_address'    => '770 Broadway, New York, NY',
                'billing_address'   => '770 Broadway, New York, NY',
                'estimate_date'     => '2026-09-02',
                'expiry_date'       => '2026-11-02',
                'total'             => '28000',
                'tax_1'             => '1400',
                'discount'          => '1000',
                'grand_total'       => '28400',
                'other_information' => 'Targeting 50M+ monthly pageviews with Cloudflare edge caching.',
                'items'             => [
                    ['item' => 'Headless CMS Architecture', 'description' => 'Laravel headless engine with GraphQL and caching layers.', 'unit_cost' => '16000', 'qty' => '1', 'amount' => '16000'],
                    ['item' => 'SEO & Speed Optimization', 'description' => 'Core Web Vitals tuning achieving 95+ PageSpeed scores.', 'unit_cost' => '12000', 'qty' => '1', 'amount' => '12000'],
                ]
            ],
        ];
        foreach ($estimates as $est) {
            $items = $est['items'];
            unset($est['items']);
            DB::table('estimates')->insert(array_merge($est, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
            foreach ($items as $itm) {
                DB::table('estimates_adds')->insert(array_merge($itm, [
                    'estimate_number' => $est['estimate_number'],
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ]));
            }
        }

        // 10. Expenses
        DB::table('expenses')->truncate();
        $expenses = [
            [
                'item_name'     => 'Amazon Web Services Cloud Infrastructure',
                'purchase_from' => 'Amazon Web Services, Inc.',
                'purchase_date' => '2026-08-01',
                'purchased_by'  => 'Sarah Jenkins',
                'amount'        => '2,840.50',
                'paid_by'       => 'Company Credit Card',
                'status'        => 'Approved',
                'attachments'   => 'photo_defaults.jpg',
            ],
            [
                'item_name'     => 'Figma Enterprise Organization Annual License',
                'purchase_from' => 'Figma Inc.',
                'purchase_date' => '2026-08-10',
                'purchased_by'  => 'Elena Rostova',
                'amount'        => '1,440.00',
                'paid_by'       => 'Bank Wire Transfer',
                'status'        => 'Approved',
                'attachments'   => 'photo_defaults.jpg',
            ],
            [
                'item_name'     => 'Dell UltraSharp 32 4K USB-C Monitors (x4)',
                'purchase_from' => 'Dell Direct Corporate',
                'purchase_date' => '2026-08-18',
                'purchased_by'  => 'David Miller',
                'amount'        => '3,196.00',
                'paid_by'       => 'Corporate Amex',
                'status'        => 'Approved',
                'attachments'   => 'photo_defaults.jpg',
            ],
            [
                'item_name'     => 'GitHub Enterprise Cloud Seats Q3',
                'purchase_from' => 'GitHub Inc.',
                'purchase_date' => '2026-08-25',
                'purchased_by'  => 'Marcus Vance',
                'amount'        => '750.00',
                'paid_by'       => 'Company Credit Card',
                'status'        => 'Approved',
                'attachments'   => 'photo_defaults.jpg',
            ],
            [
                'item_name'     => 'Annual Company Strategy Dinner & Catering',
                'purchase_from' => 'Epicurean Events SF',
                'purchase_date' => '2026-08-29',
                'purchased_by'  => 'Jayy',
                'amount'        => '1,820.00',
                'paid_by'       => 'Company Credit Card',
                'status'        => 'Approved',
                'attachments'   => 'photo_defaults.jpg',
            ],
            [
                'item_name'     => 'JetBrains All Products Pack Corporate Pack',
                'purchase_from' => 'JetBrains s.r.o.',
                'purchase_date' => '2026-09-02',
                'purchased_by'  => 'Alexander Reed',
                'amount'        => '899.00',
                'paid_by'       => 'Company Credit Card',
                'status'        => 'Pending',
                'attachments'   => 'photo_defaults.jpg',
            ],
        ];
        foreach ($expenses as $exp) {
            DB::table('expenses')->insert(array_merge($exp, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

        // 11. Jobs & Applications
        DB::table('add_jobs')->truncate();
        $jobs = [
            [
                'job_title'       => 'Senior Full-Stack Laravel Developer',
                'department'      => 'Web Department',
                'job_location'    => 'San Francisco, CA (Hybrid / Remote)',
                'no_of_vacancies' => '2',
                'experience'      => '4 - 7 Years',
                'age'             => '25',
                'salary_from'     => '95000',
                'salary_to'       => '130000',
                'job_type'        => 'Full Time',
                'status'          => 'Open',
                'start_date'      => '2026-08-01',
                'expired_date'    => '2026-10-31',
                'description'     => 'We are seeking an experienced Senior Laravel Developer to architect modern APIs, design robust relational database systems, and build scalable web applications.',
                'count'           => 42,
            ],
            [
                'job_title'       => 'Lead UI/UX Product Designer',
                'department'      => 'Product & UX Design',
                'job_location'    => 'San Francisco, CA',
                'no_of_vacancies' => '1',
                'experience'      => '5+ Years',
                'age'             => '26',
                'salary_from'     => '100000',
                'salary_to'       => '135000',
                'job_type'        => 'Full Time',
                'status'          => 'Open',
                'start_date'      => '2026-08-15',
                'expired_date'    => '2026-11-15',
                'description'     => 'Lead the UI/UX vision for our enterprise web products. Own design systems in Figma, conduct user research, and collaborate closely with engineering teams.',
                'count'           => 28,
            ],
            [
                'job_title'       => 'Cloud DevOps & Security Specialist',
                'department'      => 'IT Management',
                'job_location'    => 'Remote (US Timezones)',
                'no_of_vacancies' => '1',
                'experience'      => '3 - 6 Years',
                'age'             => '24',
                'salary_from'     => '105000',
                'salary_to'       => '140000',
                'job_type'        => 'Full Time',
                'status'          => 'Open',
                'start_date'      => '2026-08-20',
                'expired_date'    => '2026-11-30',
                'description'     => 'Manage multi-region AWS cloud environments, automate deployment pipelines with GitHub Actions, and ensure enterprise-grade security compliance.',
                'count'           => 19,
            ],
            [
                'job_title'       => 'Digital Marketing & Growth Lead',
                'department'      => 'Marketing',
                'job_location'    => 'San Francisco, CA',
                'no_of_vacancies' => '1',
                'experience'      => '3 - 5 Years',
                'age'             => '24',
                'salary_from'     => '80000',
                'salary_to'       => '105000',
                'job_type'        => 'Full Time',
                'status'          => 'Open',
                'start_date'      => '2026-09-01',
                'expired_date'    => '2026-12-01',
                'description'     => 'Drive inbound demand generation, product-led growth campaigns, search engine optimization, and enterprise customer acquisition.',
                'count'           => 15,
            ],
        ];
        foreach ($jobs as $jb) {
            DB::table('add_jobs')->insert(array_merge($jb, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

        DB::table('apply_for_jobs')->truncate();
        $applications = [
            [
                'job_title' => 'Senior Full-Stack Laravel Developer',
                'name'      => 'Michael Chang',
                'phone'     => '+1 (555) 301-4921',
                'email'     => 'm.chang.dev@gmail.com',
                'message'   => '6 years building high-throughput Laravel microservices and Vue/React frontends. Excited by your team architecture!',
                'cv_upload' => 'photo_defaults.jpg',
            ],
            [
                'job_title' => 'Senior Full-Stack Laravel Developer',
                'name'      => 'Claire Watson',
                'phone'     => '+1 (555) 492-8102',
                'email'     => 'claire.watson.engineer@gmail.com',
                'message'   => 'Staff engineer with extensive experience in Laravel queues, Redis caching, and PostgreSQL schema design.',
                'cv_upload' => 'photo_defaults.jpg',
            ],
            [
                'job_title' => 'Lead UI/UX Product Designer',
                'name'      => 'Liam O\'Connor',
                'phone'     => '+1 (555) 892-3104',
                'email'     => 'liam.design.sf@gmail.com',
                'message'   => 'Former fintech design lead with a passion for clean typography, accessibility, and robust component libraries.',
                'cv_upload' => 'photo_defaults.jpg',
            ],
            [
                'job_title' => 'Cloud DevOps & Security Specialist',
                'name'      => 'Priya Nair',
                'phone'     => '+1 (555) 773-9182',
                'email'     => 'priya.nair.cloud@gmail.com',
                'message'   => 'AWS Certified Solutions Architect with strong Terraform and Kubernetes production background.',
                'cv_upload' => 'photo_defaults.jpg',
            ],
        ];
        foreach ($applications as $app) {
            DB::table('apply_for_jobs')->insert(array_merge($app, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

        // 12. Interview Categories & Questions
        $categories = [
            'PHP & Laravel Engineering',
            'Frontend & Design Systems',
            'Database & Query Optimization',
            'Behavioral & Culture Fit'
        ];
        foreach ($categories as $cat) {
            if (!DB::table('categories')->where('category', $cat)->exists()) {
                DB::table('categories')->insert([
                    'category'   => $cat,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }

        DB::table('questions')->truncate();
        $questions = [
            [
                'category'           => 'PHP & Laravel Engineering',
                'department'         => 'Web Department',
                'questions'          => 'Which Eloquent method prevents the N+1 query problem during relational querying?',
                'option_a'           => 'Model::with() (Eager Loading)',
                'option_b'           => 'Model::loadDeferred()',
                'option_c'           => 'Model::lazy()',
                'option_d'           => 'Model::all()',
                'answer'             => 'A',
                'code_snippets'      => "User::with(['department', 'salary'])->get();",
                'answer_explanation' => 'Eager loading with with() retrieves relationships in constrained queries instead of executing a new query for each iteration.',
                'video_link'         => null,
                'image_to_question'  => 'photo_defaults.jpg',
            ],
            [
                'category'           => 'PHP & Laravel Engineering',
                'department'         => 'Web Department',
                'questions'          => 'What is the purpose of Laravel Form Requests?',
                'option_a'           => 'To render HTML forms dynamically',
                'option_b'           => 'To encapsulate validation and authorization logic away from controllers',
                'option_c'           => 'To handle CSRF token generation',
                'option_d'           => 'To perform database migrations',
                'answer'             => 'B',
                'code_snippets'      => "public function rules(): array { return ['email' => 'required|email']; }",
                'answer_explanation' => 'Custom request classes encapsulate validation and authorization logic, keeping controller methods clean and focused.',
                'video_link'         => null,
                'image_to_question'  => 'photo_defaults.jpg',
            ],
            [
                'category'           => 'Database & Query Optimization',
                'department'         => 'IT Management',
                'questions'          => 'Which index type is best suited for high cardinality equality searches and foreign keys?',
                'option_a'           => 'Fulltext Index',
                'option_b'           => 'Spatial Index',
                'option_c'           => 'B-Tree Index',
                'option_d'           => 'Hash Table Scan',
                'answer'             => 'C',
                'code_snippets'      => "\$table->index('user_id');",
                'answer_explanation' => 'B-Tree indexes are the default and most efficient general-purpose structure for sorting, range scans, and equality comparisons.',
                'video_link'         => null,
                'image_to_question'  => 'photo_defaults.jpg',
            ],
            [
                'category'           => 'Behavioral & Culture Fit',
                'department'         => 'Human Resources',
                'questions'          => 'When dealing with conflicting priority deadlines across two major stakeholders, what is the best first step?',
                'option_a'           => 'Work through the night to finish both without communicating',
                'option_b'           => 'Pick the project from the higher title stakeholder arbitrarily',
                'option_c'           => 'Proactively communicate trade-offs, align on business impact, and establish revised delivery schedules',
                'option_d'           => 'Ignore the deadlines until requested',
                'answer'             => 'C',
                'code_snippets'      => null,
                'answer_explanation' => 'Transparent communication and data-driven prioritization with key stakeholders ensures team alignment and prevents burnout.',
                'video_link'         => null,
                'image_to_question'  => 'photo_defaults.jpg',
            ],
        ];
        foreach ($questions as $q) {
            DB::table('questions')->insert(array_merge($q, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }
    }
}
